### PR TITLE
remove micropyramid

### PR DESCRIPTION
**Pull request by jagadeeshv16**
Hello,

Micropyramid doesn't provides these services, so removing it.

### CODE REVIEW

**Comment by redapple** [comment]
@ashwin31 , @jagadeeshv16 , so you want to be removed from Scrapy users section?

**Comment by jagadeeshv16** [comment]
@redapple yes

**Comment by ashwin31** [comment]
@redapple yes

**Comment by redapple** [comment]
Alright @ashwin31 , done.

**Pull request merged**
