### PR TITLE
Adding Kascale company

### PR DESCRIPTION
**Pull request by adrian-kascale**
Hi, I would like to add Kascale logo and information to companies.html. Thank you, Adrian Boczkowski, CEO of Kascale

### CODE REVIEW

**Comment by redapple** [comment]
@adrian-kascale ,
any chance you could tweet about how you use scrapy or write a blog post on what scrapy solves for you?

**Comment by adrian-kascale** [comment]
Sure, I hope to write a blog post on how to write a blog scraper (with 
very simple wordpress/blogger classifier) in a week or two.

--
Best regards,
Adrian Boczkowski
CEO of Kascale
http://kascale.com

W dniu 15.03.2016 o 16:06, Paul Tremberth pisze:

**Comment by redapple** [comment]
hi @adrian-kascale , any updates on that blog post idea?

**Comment by redapple** [comment]
kascale.com does not resolve (for me).
Thus I'm closing this one.

**Pull request closed without merging**
