### PR TITLE
added myself to list

### PR DESCRIPTION
**Pull request by Seraph2000**
Pull request for seraph_dev branch

### CODE REVIEW

**Comment by redapple** [comment]
Hi @Seraph2000 ,
we're thinking of adding a freelancers section, and it would use the same "contribution score" rules as detailed in (the new) https://github.com/scrapy/scrapy.org/blob/master/README.rst#are-you-providing-scrapy-consulting
We want to promote companies/freelancers that contribute to the Scrapy ecosystem with tutorials, code patches, blogs posts etc.

**Comment by Seraph2000** [comment]
Hi Paul,

This is an excellent idea, would love to get involved!

Seraphina

**Comment by nyov** [comment]
Ping.
This would be nice, I support it. Looks like it didn't fly, though? 3 years is a long time for a small section ;)

**Comment by redapple** [comment]
Hi all,
I'm afraid I'm not involved with scrapy or scrapy.org anymore.
Ping @Gallaecio <https://github.com/Gallaecio>

**Comment by Gallaecio** [comment]
@Seraph2000 If you are still interested, could you review https://github.com/scrapy/scrapy.org/blob/master/README.rst#adding-your-company-to-the-website ? Make sure you meet the criteria, and that you update your pull request to modify the corresponding YAML file (it looks like at least that changed since your initial submission)

**Pull request closed without merging**
