### PR TITLE
upload 404.html 

### PR DESCRIPTION
**Pull request by Rahilkaxi**

### CODE REVIEW

**Comment by Gallaecio** [comment]
What’s the source of these HTML and SVG files?

**Comment by Rahilkaxi** [comment]
SVG from bootstrap

**Comment by Rahilkaxi** [comment]
> What’s the source of these HTML and SVG files?

**Comment by Rahilkaxi** [comment]
> What’s the source of these HTML and SVG files?

My PC

**Comment by Gallaecio** [comment]
Did you copy the SVG file from somewhere, or did you create it from scratch? Why does the HTML have so much code for a simple 404 page? Why is there a “Return” word in the page, is it meant to link somewhere?

**Comment by Rahilkaxi** [comment]
> Did you copy the SVG file from somewhere, or did you create it from scratch? Why does the HTML have so much code for a simple 404 page? Why is there a “Return” word in the page, is it meant to link somewhere?


Yes! The css I from bootstrap staticfiles and the return word redirect you to home page after writing the home page link in href tag

**Comment by Gallaecio** [comment]
What’s the license of the SVG file? Where does it come from?

**Comment by Rahilkaxi** [comment]
> What’s the license of the SVG file? Where does it come from?

Bootstrap

**Comment by Gallaecio** [comment]
The website is not ready to render 404 pages, it returns 403 for missing pages at the moment, so adding a 404 is pointless before we make it so that the server actually sends those.

**Pull request closed without merging**
