### PR TITLE
Added datrock.co to the companies list

### PR DESCRIPTION
**Pull request by vilnitskiy**

### CODE REVIEW

**Comment by vilnitskiy** [comment]
@redapple hi, could you please take a look on this PR?

**Comment by redapple** [comment]
hi @vilnitskiy , I'm not really involved much in scrapy and scrapy.org these days.
I'd ask @pablohoffman for a review/merge.

**Comment by vilnitskiy** [comment]
Hi @pablohoffman, could you please take a look on this pull request?

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy.org#adding-your-company-to-the-website

**Pull request closed without merging**
