### PR TITLE
add micropyramid company

### PR DESCRIPTION
**Pull request by ashwin31**
reference to our expertise

https://micropyramid.com/blog/scrape-website-using-scrapy-python/
https://micropyramid.com/blog/export-data-with-scrapy-python/

### CODE REVIEW

**Comment by ashwin31** [comment]
Hi @redapple can you review this :heart_eyes:

**Comment by dangra** [comment]
@ashwin31 both blogpost looks good and the PR too. Would be nice to add a link back to https://scrapy.org from the blogposts.

**Comment by ashwin31** [comment]
@dangra I have added links to scrapy from those blogs posts.

**Comment by redapple** [comment]
@ashwin31 , website has been updated. Sorry it took so long.

**Pull request merged**
