### PR TITLE
Adding WatchPatrol to companies that use Scrapy section of website

### PR DESCRIPTION
**Pull request by migganimon**

### CODE REVIEW

**Comment by migganimon** [comment]
Hi Scrapy Team, is there anything else I need to do to get this pull request merged?

**Comment by migganimon** [comment]
No worries!   
  
  
  

  
  
My blog isn’t development focused, and I doubt my audience would care (or understand), but I could add a scrapy link to my product announcement at   
  https://www.60clicks.com/introducing-watchpatrol (https://www.60clicks.com/introducing-watchpatrol/)   if it would help.     

  
Mike
  
>

**Comment by pablohoffman** [comment]
That would be helpful, once there is a public mention we can include the link in scrapy.org. Open source projects that use Scrapy don't have this restriction as their code is available and people can see they use Scrapy.

**Comment by migganimon** [comment]
OK Pablo -- the link to Scrapy has been added to the article at https://www.60clicks.com/introducing-watchpatrol/ near the bottom in the technology section.

**Pull request merged**
