### PR TITLE
Added a Company

### PR DESCRIPTION
**Pull request by SylvainTI**
Added cocon.se , a dataviz tool using scrapy for dev & prod.

### CODE REVIEW

**Comment by redapple** [comment]
Hi @SylvainTI , any chance you could tweet or blog about how you use Scrapy at cocon.se?

**Comment by SylvainTI** [comment]
Sure. Here is a blog post : http://cocon.se/cocon-semantique/devs/scrapy/

**Comment by redapple** [comment]
Thanks @SylvainTI !
By the way, if you're looking at extracting embedded microdata from HTML, you can check https://github.com/scrapinghub/extruct
[I started working on an lxml-based RDFa parser](https://github.com/scrapinghub/extruct/pull/26) but still need to resume this.
I would be happy to have cocon.se's feedback on the library.

**Comment by SylvainTI** [comment]
Will check, thanks !

**Pull request merged**
