### PR TITLE
Use github actions to build and publish site to S3

### PR DESCRIPTION
**Pull request by cyberplant**

### CODE REVIEW

**Comment by pablohoffman** [comment]
do you know who can review this @kmike?. I'm not familiar with Github Actions myself

**Comment by kmike** [comment]
We use Github Actions in many projects now, @Gallaecio should be familiar with them :) 

Here the code should do the same as travis.yml file; it'd be better to remove travis.yml file in the same PR.

@cyberplant travis.yml also invalidates cloudflare caches; shouldn't we do the same here?

**Comment by cyberplant** [comment]
Hello guys!

I'm new to Github Actions so I'm learning it and doing couple tests.

I'll ping here again when I'm done so we can all review it!

**Comment by cyberplant** [comment]
It's *alive*! 😄 

On [this build](https://github.com/scrapy/scrapy.org/actions/runs/1056692974
) I synced to a [test subdirectory](https://scrapy.org/test/)

Looks like it's working fine! Only remains to change the endpoint to be the root instead of the subdirectory on the secrets and we're done. I'm leaving this on /test right now in case you want to test something else.

**Comment by Gallaecio** [comment]
Looks good to me. I vote for you to update the secret to point to the root, and then merge, so that the latest commit get deployed right away.

**Comment by cyberplant** [comment]
Done, let's see how it goes!

**Comment by Gallaecio** [comment]
It worked like a charm: You can now see “New” besides “Discord” in https://scrapy.org/community/ (may need to refresh)

**Comment by cyberplant** [comment]
Finished, and it's looking fine. 

To be sure it applied I checked on [this page](https://scrapy.org/community/) where we can see the NEW on Discord link, that was the previous commit to my changes.

**Pull request merged**
